name: SNBPlugin
main: gbovv.com.SNBPlugin
version: 1.0
api-version: 1.21
folia-supported: true
commands:
  snb:
    description: 发送弹幕
  snbreload:
    description: 重载插件配置
    permission: snb.admin
permissions:
  snb.admin:
    description: 管理弹幕配置
    default: op
  snb.use:
    description: 允许发送弹幕消息
    default: true
    children:
      snb.admin: false
settings:
  max-length: 50
  default-speed: 3
 